const BIBLIOTHEQUE = {
    anglais: [
        {
            niveau: 1,
            titre: "Imagine",
            artiste: "John Lennon",
            fichier: "songs/anglais/anglais_1.mp3",
            ambiance: "#87CEEB", // Bleu ciel
            paroles: [
                { t: 0.0, texte: "♪ (Background sounds)", trad: "♪ (Ambiance et bruits de pas)" },
                { t: 40.0, texte: "♪ (Piano starts)" , trad: "♪ (Le piano commence)" },
                { t: 54.1, texte: "Imagine there's no heaven", trad: "Imagine qu'il n'y a pas de paradis" },
                { t: 60.2, texte: "It's easy if you try", trad: "C'est facile si tu essaies" },
                { t: 67, texte: "No hell below us", trad: "Aucun enfer en dessous de nous" },
                { t: 74, texte: "Above us, only sky", trad: "Au-dessus de nous, seulement le ciel" },
                { t: 79.8, texte: "Imagine all the people", trad: "Imagine tous les gens" },
                { t: 85.8, texte: "Living for today... Ah-ah", trad: "Vivant pour aujourd'hui... Ah-ah" },
                { t: 91.8, texte: "Imagine there's no countries", trad: "Imagine qu'il n'y a pas de pays" },
                { t: 98.8, texte: "It isn't hard to do", trad: "Ce n'est pas dur à faire" },
                { t: 105, texte: "Nothing to kill or die for", trad: "Rien pour quoi tuer ou mourir" },
                { t: 111.2, texte: "And no religion, too", trad: "Et pas de religion, non plus" },
                { t: 118.9, texte: "Imagine all the people", trad: "Imagine tous les gens" },
                { t: 125, texte: "Living life in peace... You-hou", trad: "Vivant leur vie en paix... You-hou" },
                { t: 130.7, texte: "You may say I'm a dreamer", trad: "Tu peux dire que je suis un rêveur" },
                { t: 137.9, texte: "But I'm not the only one", trad: "Mais je ne suis pas le seul" },
                { t: 143.8, texte: "I hope someday you'll join us", trad: "J'espère qu'un jour tu nous rejoindras" },
                { t: 150, texte: "And the world will be as one", trad: "Et que le monde ne fera qu'un" },
                { t: 156, texte: "Imagine no possessions", trad: "Imagine aucune possession" },
                { t: 163, texte: "I wonder if you can", trad: "Je me demande si tu le peux" },
                { t: 168.5, texte: "No need for greed or hunger", trad: "Pas besoin d'avidité ou de faim" },
                { t: 175, texte: "A brotherhood of man", trad: "Une fraternité humaine" },
                { t: 180.8, texte: "Imagine all the people", trad: "Imagine tous les gens" },
                { t: 186.8, texte: "Sharing all the world... You-hou", trad: "Partageant le monde entier... You-hou" },
                { t: 194.6, texte: "You may say I'm a dreamer", trad: "Tu peux dire que je suis un rêveur" },
                { t: 200.8, texte: "But I'm not the only one", trad: "Mais je ne suis pas le seul" },
                { t: 206.9, texte: "I hope someday you'll join us", trad: "J'espère qu'un jour tu nous rejoindras" },
                { t: 213.8, texte: "And the world will live as one", trad: "Et que le monde vivra comme un seul" }
            ]
        },
        {
            niveau: 2,
            titre: "Flowers",
            artiste: "Miley Cyrus",
            fichier: "songs/anglais/flowers.mp3",
            ambiance: "#FFD700", // Or (Miley Gold)
            paroles: [
                { t: 0.0, texte: "♪ (Silence)", trad: "♪ (Silence)" },
                { t: 3.7, texte: "♪ (Musique)", trad: "♪ (Musique)" },
                { t: 7.8, texte: "We were good, we were gold", trad: "On était bien, on était de l'or" },
                { t: 12.2, texte: "Kind of dream that can't be sold", trad: "Le genre de rêve qui ne s'achète pas" },
                { t: 16.2, texte: "We were right 'til we weren't", trad: "On avait raison jusqu'à ce qu'on ait tort" },
                { t: 20.3, texte: "Built a home and watched it burn", trad: "On a construit un foyer et on l'a regardé brûler" },
                { t: 24.4, texte: "Mm, I didn't wanna leave you", trad: "Mm, je ne voulais pas te quitter" },
                { t: 26.8, texte: "I didn't wanna lie", trad: "Je ne voulais pas mentir" },
                { t: 28.7, texte: "Started to cry but then remembered I", trad: "J'ai commencé à pleurer, puis je me suis souvenue que je..." },
                { t: 33.4, texte: "I can buy myself flowers", trad: "Je peux m'acheter des fleurs toute seule" },
                { t: 37.7, texte: "Write my name in the sand", trad: "Écrire mon nom dans le sable" },
                { t: 41.5, texte: "Talk to myself for hours", trad: "Me parler à moi-même pendant des heures" },
                { t: 45.5, texte: "Say things you don't understand", trad: "Dire des choses que tu ne comprends pas" },
                { t: 49.7, texte: "I can take myself dancing", trad: "Je peux m'emmener danser" },
                { t: 51.5, texte: "And I can hold my own hand", trad: "Et je peux me tenir la main" },
                { t: 54.2, texte: "Yeah, I can love me better than you can", trad: "Ouais, je peux m'aimer mieux que tu ne le peux" },
                { t: 58.7, texte: "Can love me better", trad: "M'aimer mieux" },
                { t: 60.5, texte: "I can love me better, baby", trad: "Je peux m'aimer mieux, bébé" },
                { t: 62.9, texte: "Can love me better", trad: "M'aimer mieux" },
                { t: 64.6, texte: "I can love me better, baby", trad: "Je peux m'aimer mieux, bébé" },
                { t: 67.4, texte: "Paint my nails, cherry red", trad: "Me peindre les ongles en rouge cerise" },
                { t: 71.0, texte: "Match the roses that you left", trad: "Assortis aux roses que tu as laissées" },
                { t: 75.1, texte: "No remorse, no regret", trad: "Sans remords, sans regret" },
                { t: 79.1, texte: "I forgive every word you said", trad: "Je pardonne chaque mot que tu as dit" },
                { t: 83.4, texte: "Ooh, I didn't wanna leave you, baby", trad: "Ooh, je ne voulais pas te quitter, bébé" },
                { t: 85.9, texte: "I didn't wanna fight", trad: "Je ne voulais pas me battre" },
                { t: 87.7, texte: "Started to cry but then remembered I", trad: "J'ai commencé à pleurer, puis je me suis souvenue que je..." },
                { t: 92.5, texte: "I can buy myself flowers", trad: "Je peux m'acheter des fleurs toute seule" },
                { t: 96.6, texte: "Write my name in the sand", trad: "Écrire mon nom dans le sable" },
                { t: 100.4, texte: "Talk to myself for hours, mm", trad: "Me parler à moi-même pendant des heures, mm" },
                { t: 104.6, texte: "Say things you don't understand", trad: "Dire des choses que tu ne comprends pas" },
                { t: 108.8, texte: "I can take myself dancing, mm", trad: "Je peux m'emmener danser, mm" },
                { t: 112.8, texte: "And I can hold my own hand", trad: "Et je peux me tenir la main" },
                { t: 115.7, texte: "Yeah, I can love me better than you can", trad: "Ouais, je peux m'aimer mieux que tu ne le peux" },
                { t: 120.9, texte: "Can love me better", trad: "M'aimer mieux" },
                { t: 122.3, texte: "I can love me better, baby", trad: "Je peux m'aimer mieux, bébé" },
                { t: 124.9, texte: "Can love me better", trad: "M'aimer mieux" },
                { t: 126.2, texte: "I can love me better, baby", trad: "Je peux m'aimer mieux, bébé" },
                { t: 128.7, texte: "Can love me better", trad: "M'aimer mieux" },
                { t: 130.5, texte: "I can love me better, baby", trad: "Je peux m'aimer mieux, bébé" },
                { t: 133.0, texte: "Can love me better I...", trad: "M'aimer mieux, je..." },
                { t: 136.2, texte: "I didn't wanna leave you, I didn't wanna fight", trad: "Je ne voulais pas te quitter, je ne voulais pas me battre" },
                { t: 140.2, texte: "Started to cry but then remembered I", trad: "J'ai commencé à pleurer, puis je me suis souvenue que je..." },
                { t: 144.5, texte: "I can buy myself flowers (Uh-huh)", trad: "Je peux m'acheter des fleurs toute seule (Uh-huh)" },
                { t: 148.8, texte: "Write my name in the sand", trad: "Écrire mon nom dans le sable" },
                { t: 152.7, texte: "Talk to myself for hours (Yeah)", trad: "Me parler à moi-même pendant des heures (Yeah)" },
                { t: 156.9, texte: "Say things you don't understand", trad: "Dire des choses que tu ne comprends pas" },
                { t: 161.2, texte: "I can take myself dancing", trad: "Je peux m'emmener danser" },
                { t: 165.1, texte: "And I can hold my own hand", trad: "Et je peux me tenir la main" },
                { t: 168.8, texte: "Yeah, I can love me better than", trad: "Ouais, je peux m'aimer mieux que..." },
                { t: 173.0, texte: "Yeah, I can love me better than you can", trad: "Ouais, je peux m'aimer mieux que tu ne le peux" },
                { t: 177.6, texte: "Can love me better", trad: "M'aimer mieux" },
                { t: 179.1, texte: "I can love me better, baby (Uh)", trad: "Je peux m'aimer mieux, bébé (Uh)" },
                { t: 181.7, texte: "Can love me better", trad: "M'aimer mieux" },
                { t: 183.1, texte: "I can love me better, baby (Than you can)", trad: "Je peux m'aimer mieux, bébé (Que tu ne le peux)" },
                { t: 185.6, texte: "Can love me better", trad: "M'aimer mieux" },
                { t: 187.4, texte: "I can love me better, baby", trad: "Je peux m'aimer mieux, bébé" },
                { t: 190.2, texte: "Can love me better I...", trad: "M'aimer mieux, je..." }
            ]
        },
        {
            niveau: 3,
            titre: "Bohemian Rhapsody",
            artiste: "Queen",
            fichier: "songs/anglais/anglais_3.mp3",
            ambiance: "#4B0082", 
            paroles: [
                { t: 1.9, texte: "Is this the real life?", trad: "Est-ce la vraie vie ?" },
                { t: 5.5, texte: "Is this just fantasy?", trad: "Est-ce juste un fantasme ?" },
                { t: 8.8, texte: "Caught in a landslide, no escape from reality", trad: "Pris dans un glissement de terrain, aucune échappatoire à la réalité" },
                { t: 16.6, texte: "Open your eyes, look up to the skies and see", trad: "Ouvre les yeux, regarde vers le ciel et vois" },
                { t: 27.4, texte: "I'm just a poor boy,", trad: "Je ne suis qu'un pauvre garçon," },
                { t: 30.6, texte: "I need no sympathy", trad: "Je n'ai pas besoin de pitié" },
                { t: 33.0, texte: "Because I'm easy come, easy go, little high, little low", trad: "Parce que je vais et je viens, un peu haut, un peu bas" },
                { t: 40.2, texte: "Any way the wind blows doesn't really matter to me, to me", trad: "Peu importe d'où vient le vent, cela n'a pas d'importance pour moi" },
                { t: 57.6, texte: "Mama, just killed a man", trad: "Maman, je viens de tuer un homme" },
                { t: 64.1, texte: "Put a gun against his head, pulled my trigger, now he's dead", trad: "J'ai mis un pistolet contre sa tête, j'ai pressé la détente, maintenant il est mort" },
                { t: 71.0, texte: "Mama, life had just begun", trad: "Maman, la vie venait de commencer" },
                { t: 77.4, texte: "But now I've gone and thrown it all away", trad: "Mais maintenant je suis parti et j'ai tout gâché" },
                { t: 84.5, texte: "Mama, ooh, didn't mean to make you cry", trad: "Maman, ooh, je ne voulais pas te faire pleurer" },
                { t: 94.7, texte: "If I'm not back again this time tomorrow", trad: "Si je ne suis pas de retour demain à cette heure" },
                { t: 99.4, texte: "Carry on, carry on as if nothing really matters", trad: "Continue, continue comme si rien n'avait d'importance" },
                { t: 114.5, texte: "Too late, my time has come", trad: "Trop tard, mon heure a sonné" },
                { t: 121.4, texte: "Sends shivers down my spine, body's aching all the time", trad: "Des frissons me parcourent l'échine, mon corps souffre tout le temps" },
                { t: 128.3, texte: "Goodbye, everybody, I've got to go", trad: "Adieu tout le monde, je dois y aller" },
                { t: 135.0, texte: "Gotta leave you all behind and face the truth", trad: "Je dois tous vous laisser derrière moi et affronter la vérité" },
                { t: 141.7, texte: "Mama, ooh (Any way the wind blows)", trad: "Maman, ooh (Peu importe d'où vient le vent)" },
                { t: 148.7, texte: "I don't wanna die", trad: "Je ne veux pas mourir" },
                { t: 152.1, texte: "I sometimes wish I'd never been born at all", trad: "Je souhaite parfois ne jamais être né du tout" },
                { t: 159.1, texte: "♪ (Guitar Solo)", trad: "♪ (Solo de guitare)" },
                { t: 188.2, texte: "I see a little silhouetto of a man", trad: "Je vois une petite silhouette d'homme" },
                { t: 190.9, texte: "Scaramouche, Scaramouche, will you do the Fandango?", trad: "Scaramouche, Scaramouche, vas-tu danser le Fandango ?" },
                { t: 194.6, texte: "Thunderbolt and lightning, very, very frightening me", trad: "Le tonnerre et la foudre, m'effraient énormément" },
                { t: 198.1, texte: "(Galileo) Galileo,", trad: "(Galileo) Galileo," },
                { t: 199.7, texte: "(Galileo) Galileo,", trad: "(Galileo) Galileo," },
                { t: 201.6, texte: "Galileo Figaro, magnifico", trad: "Galileo Figaro, magnifique" },
                { t: 204.9, texte: "But I'm just a poor boy, nobody loves me", trad: "Mais je ne suis qu'un pauvre garçon, personne ne m'aime" },
                { t: 207.9, texte: "He's just a poor boy from a poor family", trad: "C'est juste un pauvre garçon d'une famille pauvre" },
                { t: 211.1, texte: "Spare him his life from this monstrosity", trad: "Épargnez sa vie de cette monstruosité" },
                { t: 216.1, texte: "Easy come, easy go, will you let me go?", trad: "Je vais, je viens, me laisserez-vous partir ?" },
                { t: 218.9, texte: "Bismillah!", trad: "Bismillah (Au nom de Dieu) !" },
                { t: 220.0, texte: "No, we will not let you go (Let him go!)", trad: "Non, nous ne te laisserons pas partir (Laissez-le partir !)" },
                { t: 222.5, texte: "Bismillah!", trad: "Bismillah !" },
                { t: 223.8, texte: "We will not let you go (Let him go!)", trad: "Nous ne te laisserons pas partir (Laissez-le partir !)" },
                { t: 225.8, texte: "Bismillah!", trad: "Bismillah !" },
                { t: 226.9, texte: "We will not let you go (Let me go!)", trad: "Nous ne te laisserons pas partir (Laissez-moi partir !)" },
                { t: 228.5, texte: "Will not let you go (Let me go!)", trad: "On ne te laissera pas partir (Laissez-moi partir !)" },
                { t: 230.1, texte: "Never, never, never, never let me go", trad: "Jamais, jamais, jamais, jamais ne me laissez partir" },
                { t: 233.4, texte: "Oh, oh, oh, oh", trad: "Oh, oh, oh, oh" },
                { t: 235.2, texte: "No, no, no, no, no, no, no", trad: "Non, non, non, non, non, non, non" },
                { t: 238.5, texte: "Oh, mamma mia, mamma mia (Mamma mia, let me go)", trad: "Oh, mamma mia, mamma mia (Mamma mia, laisse-moi partir)" },
                { t: 241.6, texte: "Beelzebub has a devil put aside for me, for me, for me!", trad: "Belzébuth a un diable de côté pour moi, pour moi !" },
                { t: 252.4, texte: "So you think you can stone me and spit in my eye?", trad: "Alors tu penses pouvoir me lapider et me cracher au visage ?" },
                { t: 257.3, texte: "So you think you can love me and leave me to die?", trad: "Alors tu penses pouvoir m'aimer et m'abandonner à la mort ?" },
                { t: 262.4, texte: "Oh, baby, can't do this to me, baby!", trad: "Oh, bébé, tu ne peux pas me faire ça, bébé !" },
                { t: 267.4, texte: "Just gotta get out, just gotta get right outta here!", trad: "Je dois juste sortir, je dois juste sortir d'ici !" },
                { t: 275.0, texte: "♪ (Guitar Outro)", trad: "♪ (Sortie à la guitare)" },
                { t: 313.0, texte: "Nothing really matters, anyone can see", trad: "Rien n'a vraiment d'importance, tout le monde peut le voir" },
                { t: 321.4, texte: "Nothing really matters", trad: "Rien n'a vraiment d'importance" },
                { t: 326.8, texte: "Nothing really matters to me", trad: "Rien n'a vraiment d'importance pour moi" },
                { t: 334.0, texte: "Any way the wind blows...", trad: "Peu importe d'où vient le vent..." }
            ]
        },
        {
            niveau: 4,
            titre: "Rap God",
            artiste: "Eminem",
            fichier: "songs/anglais/anglais_4.mp3",
            ambiance: "#FF0000",
            paroles: [
                { t: 1.447, texte: "Look, I was gonna go easy on you not to hurt your feelings.", trad: "Écoute, j'allais y aller doucement pour ne pas te blesser." },
                { t: 5.062, texte: "But I'm only going to get this one chance.", trad: "Mais je n'aurai qu'une seule chance." },
                { t: 9.505, texte: "Something's wrong, I can feel it.", trad: "Quelque chose ne va pas, je le sens." },
                { t: 11.922, texte: "Six minutes, Slim Shady, you're on!", trad: "Six minutes, Slim Shady, c'est à toi !" },
                { t: 11.703, texte: "Just a feeling I've got.", trad: "C'est juste un pressentiment que j'ai." },
                { t: 14.480, texte: "Like something's about to happen, but I don't know what.", trad: "Comme si quelque chose allait arriver, mais je ne sais pas quoi." },
                { t: 18.010, texte: "If that means what I think it means, we're in trouble, big trouble;", trad: "Si ça veut dire ce que je pense, on est dans le pétrin, un sacré pétrin ;" },
                { t: 21.000, texte: "and if he is as bananas as you say, I'm not taking any chances.", trad: "et s'il est aussi timbré que tu le dis, je ne prends aucun risque." },
                { t: 24.669, texte: "You are just what the doc ordered.", trad: "Tu es pile ce que le docteur a prescrit." },
                { t: 26.152, texte: "I'm beginnin' to feel like a Rap God, Rap God", trad: "Je commence à me sentir comme un Dieu du Rap, Dieu du Rap" },
                { t: 29.257, texte: "All my people from the front to the back nod, back nod", trad: "Tous les miens, de l'avant vers l'arrière, hochez la tête" },
                { t: 32.505, texte: "Now, who thinks their arms are long enough to slap box, slap box?", trad: "Maintenant, qui pense avoir les bras assez longs pour boxer ?" },
                { t: 35.693, texte: "They said I rap like a robot, so call me Rap-bot", trad: "Ils disent que je rappe comme un robot, appelez-moi Rap-bot" },
                { t: 38.189, texte: "But for me to rap like a computer it must be in my genes", trad: "Mais pour que je rappe comme un ordi, ça doit être dans mes gènes" },
                { t: 40.253, texte: "I got a laptop in my back pocket", trad: "J'ai un ordi portable dans ma poche arrière" },
                { t: 42.202, texte: "My pen'll go off when I half-cock it", trad: "Mon stylo dégaine dès que je l'arme à moitié" },
                { t: 43.795, texte: "Got a fat knot from that rap profit", trad: "J'ai une liasse épaisse grâce aux profits du rap" },
                { t: 45.314, texte: "Made a livin' and a killin' off it", trad: "J'en ai fait mon gagne-pain et un massacre" },
                { t: 46.565, texte: "Ever since Bill Clinton was still in office", trad: "Depuis l'époque où Bill Clinton était encore au bureau" },
                { t: 48.138, texte: "With Monica Lewinsky feelin' on his nutsack", trad: "Avec Monica Lewinsky qui lui tâtonnait les bourses" },
                { t: 50.288, texte: "I'm an MC still as honest", trad: "Je suis un MC toujours aussi honnête" },
                { t: 51.582, texte: "But as rude and as indecent as all hell", trad: "Mais aussi impoli et indécent que l'enfer" },
                { t: 53.109, texte: "Syllables, skill-a-holic (Kill 'em all with)", trad: "Syllabes, accro à la technique (Tue-les tous avec)" },
                { t: 54.895, texte: "This flippity dippity-hippity hip-hop", trad: "Ce hip-hop virevoltant et bondissant" },
                { t: 56.055, texte: "You don't really wanna get into a pissin' match", trad: "Tu ne veux pas vraiment entrer dans un concours de pisse" },
                { t: 57.569, texte: "With this rappity brat, packin' a MAC in the back of the Ac'", trad: "Avec ce gosse du rap, cachant un MAC à l'arrière de l'Acra" },
                { t: 59.824, texte: "Backpack rap crap, yap-yap, yackety-yack", trad: "Ce rap de sac à dos, bla-bla, yackety-yack" },
                { t: 61.698, texte: "And at the exact same time, I attempt these lyrical acrobat stunts while I'm practicin' that", trad: "Et au même moment, je tente ces acrobaties lyriques tout en m'entraînant" },
                { t: 64.867, texte: "I'll still be able to break a motherfuckin' table", trad: "Je serai toujours capable de briser une putain de table" },
                { t: 66.196, texte: "Over the back of a couple of faggots and crack it in half", trad: "Sur le dos de quelques types et la casser en deux" },
                { t: 68.186, texte: "Only realized it was ironic, I was signed to Aftermath after the fact", trad: "J'ai réalisé l'ironie, j'ai signé chez Aftermath après coup" },
                { t: 71.468, texte: "How could I not blow? All I do is drop F-bombs", trad: "Comment ne pas exploser ? Je ne fais que lâcher des bombes" },
                { t: 73.806, texte: "Feel my wrath of attack", trad: "Ressens la colère de mon attaque" },
                { t: 74.667, texte: "Rappers are havin' a rough time period, here's a maxi pad", trad: "Les rappeurs ont une période difficile, voici une serviette" },
                { t: 77.282, texte: "It's actually disastrously bad for the wack", trad: "C'est en fait désastreux pour les nuls" },
                { t: 79.022, texte: "While I'm masterfully constructing this masterpiece as", trad: "Pendant que je construis magistralement ce chef-d'œuvre" },
                { t: 81.125, texte: "'Cause I'm beginnin' to feel like a Rap God, Rap God", trad: "Parce que je commence à me sentir comme un Dieu du Rap" },
                { t: 84.413, texte: "All my people from the front to the back nod, back nod", trad: "Tous les miens, de l'avant vers l'arrière, hochez la tête" },
                { t: 87.621, texte: "Now, who thinks their arms are long enough to slap box, slap box?", trad: "Maintenant, qui pense avoir les bras assez longs pour boxer ?" },
                { t: 90.791, texte: "Let me show you maintainin' this shit ain't that hard, that hard", trad: "Laisse-moi te montrer que maintenir ce niveau n'est pas si dur" },
                { t: 94.095, texte: "Everybody wants the key and the secret to rap immortality like Ι have got.", trad: "Tout le monde veut la clé et le secret de l'immortalité du rap que j'ai." },
                { t: 97.000, texte: "Well, to be truthful the blueprint's simply rage and youthful exuberance", trad: "Pour être franc, le plan c'est juste la rage et l'exubérance de la jeunesse" },
                { t: 98.279, texte: "Simply rage and youthful exuberance", trad: "Simplement de la rage et de l'exubérance juvénile" },
                { t: 100.080, texte: "Everybody loves to root for a nuisance", trad: "Tout le monde aime encourager une nuisance" },
                { t: 101.471, texte: "Hit the Earth like an asteroid", trad: "J'ai frappé la Terre comme un astéroïde" },
                { t: 102.548, texte: "Did nothing but shoot for the Moon since (Pew!)", trad: "Je n'ai fait que viser la lune depuis (Pew !)" },
                { t: 104.669, texte: "MCs get taken to school with this music", trad: "Les MCs retournent à l'école avec cette musique" },
                { t: 106.269, texte: "'Cause I use it as a vehicle to 'bus the rhyme'", trad: "Car je l'utilise comme un véhicule pour 'envoyer la rime'" },
                { t: 108.279, texte: "Now I lead a new school full of students", trad: "Maintenant je dirige une nouvelle école pleine d'étudiants" },
                { t: 109.958, texte: "Me?", trad: "Moi ?" },
                { t: 110.000, texte: "I'm a product of Rakim, Lakim Shabazz, 2Pac, N.W.A, Cube, hey Doc, Ren", trad: "Je suis un produit de Rakim, Lakim Shabazz, 2Pac, N.W.A, Cube, hey Doc, Ren" },
                { t: 114.464, texte: "Yella, Eazy, thank you, they got Slim", trad: "Yella, Eazy, merci, ils ont eu Slim" },
                { t: 116.411, texte: "Inspired enough to one day grow up, blow up and be in a position", trad: "Assez inspiré pour un jour grandir, exploser et être en position" },
                { t: 119.544, texte: "To meet Run–D.M.C., induct them", trad: "De rencontrer Run-D.M.C., de les introduire" },
                { t: 120.929, texte: "Into the motherfuckin' Rock and Roll Hall of Fame", trad: "Au putain de Rock and Roll Hall of Fame" },
                { t: 123.712, texte: "Even though I'll walk in the church and burst in a ball of flames", trad: "Même si j'entrerai dans l'église en explosant en boules de feu" },
                { t: 126.133, texte: "Only Hall of Fame I'll be inducted in is the alcohol of fame", trad: "Le seul Hall of Fame où je serai, c'est celui de l'alcool" },
                { t: 128.984, texte: "On the wall of shame", trad: "Sur le mur de la honte" },
                { t: 130.088, texte: "You fags think it's all a game, 'til I walk a flock of flames", trad: "Vous croyez que c'est un jeu, jusqu'à ce que j'amène les flammes" },
                { t: 133.547, texte: "Off a plank and, tell me what in the fuck are you thinkin'?", trad: "Du haut d'une planche, dis-moi à quoi tu penses putain ?" },
                { t: 136.315, texte: "Little gay-lookin' boy", trad: "Petit garçon à l'air gai" },
                { t: 137.208, texte: "So gay I can barely say it with a straight face, lookin' boy", trad: "Si gai que je peux à peine le dire sans rire" },
                { t: 139.477, texte: "You're witnessin' a massacre", trad: "Tu es témoin d'un massacre" },
                { t: 140.643, texte: "Like you're watching a church gathering take place, lookin' boy", trad: "Comme si tu regardais un rassemblement à l'église" },
                { t: 143.203, texte: "'Oy vey, that boy's gay!'—that's all they say, lookin' boy", trad: "'Oy vey, ce garçon est gai !' — c'est tout ce qu'ils disent" },
                { t: 146.092, texte: "You get a thumbs up, pat on the back", trad: "Tu reçois un pouce levé, une tape dans le dos" },
                { t: 147.416, texte: "And a 'way to go' from your label every day, lookin' boy", trad: "Et un 'bravo' de ton label chaque jour" },
                { t: 149.408, texte: "Hey, lookin' boy!", trad: "Hé, mon gars !" },
                { t: 150.792, texte: "What you say, lookin' boy? I get a 'hell yeah' from Dre, lookin' boy", trad: "Qu'est-ce que tu dis ? J'obtiens un 'hell yeah' de Dre" },
                { t: 152.579, texte: "I'ma work for everything I have, never ask nobody for shit", trad: "Je vais bosser pour tout ce que j'ai, sans rien demander" },
                { t: 154.830, texte: "Get outta my face, lookin' boy!", trad: "Dégage de là, mon gars !" },
                { t: 155.774, texte: "Basically, boy, you're never gonna be capable", trad: "En gros, tu ne seras jamais capable" },
                { t: 157.358, texte: "Of keepin' up with the same pace, lookin' boy, 'cause—", trad: "De tenir le même rythme, mon gars, parce que—" },
                { t: 159.197, texte: "I'm beginnin' to feel like a Rap God, Rap God", trad: "Je commence à me sentir comme un Dieu du Rap" },
                { t: 162.207, texte: "All my people from the front to the back nod, back nod", trad: "Tous les miens, de l'avant vers l'arrière, hochez la tête" },
                { t: 165.412, texte: "The way I'm racin' around the track, call me NASCAR, NASCAR", trad: "Vu comment je fonce sur la piste, appelle-moi NASCAR" },
                { t: 168.544, texte: "Dale Earnhardt of the trailer park, the White Trash God", trad: "Dale Earnhardt du parc de caravanes, le Dieu White Trash" },
                { t: 171.195, texte: "Kneel before General Zod", trad: "Agenouille-toi devant le Général Zod" },
                { t: 172.379, texte: "This planet's Krypton—no, Asgard, Asgard", trad: "Cette planète est Krypton — non, Asgard" },
                { t: 175.149, texte: "So you'll be Thor and I'll be Odin", trad: "Alors tu seras Thor et je serai Odin" },
                { t: 177.132, texte: "You rodent, I'm omnipotent", trad: "Espèce de rongeur, je suis omnipotent" },
                { t: 178.703, texte: "Let off, then I'm reloadin'", trad: "Je lâche tout, puis je recharge" },
                { t: 180.270, texte: "Immediately with these bombs, I'm totin'", trad: "Immédiatement avec ces bombes que je transporte" },
                { t: 181.944, texte: "And I should not be woken", trad: "Et on ne devrait pas me réveiller" },
                { t: 183.662, texte: "I'm the walkin' dead, but I'm just a talkin' head, a zombie floatin'", trad: "Je suis un mort-vivant, juste une tête qui parle, un zombie qui flotte" },
                { t: 186.957, texte: "But I got your mom deep-throatin'", trad: "Mais j'ai ta mère qui me fait une gâterie" },
                { t: 188.649, texte: "I'm out my Ramen Noodle", trad: "Je n'ai plus mes nouilles Ramen (je suis fou)" },
                { t: 189.905, texte: "We have nothin' in common, poodle", trad: "On n'a rien en commun, caniche" },
                { t: 191.560, texte: "I'm a Doberman, pinch yourself in the arm and pay homage, pupil", trad: "Je suis un Doberman, pince-toi le bras et rends hommage" },
                { t: 195.136, texte: "It's me, my honesty's brutal", trad: "C'est moi, mon honnêteté est brutale" },
                { t: 197.568, texte: "But it's honestly futile if I don't utilize what I do though", trad: "Mais c'est futile si je n'utilise pas ce que je fais" },
                { t: 200.840, texte: "For good at least once in a while", trad: "Pour le bien au moins de temps en temps" },
                { t: 201.860, texte: "So I wanna make sure somewhere in this chicken scratch I scribble enough rhymes", trad: "Alors je veux m'assurer que dans ce gribouillage j'écris assez de rimes" },
                { t: 205.211, texte: "To maybe try to help get some people through tough times", trad: "Pour peut-être aider les gens à traverser les moments difficiles" },
                { t: 207.801, texte: "But I gotta keep a few punchlines", trad: "Mais je dois garder quelques punchlines" },
                { t: 209.091, texte: "Just in case, 'cause even you unsigned", trad: "Au cas où, car même vous, sans label" },
                { t: 210.732, texte: "Rappers are hungry lookin' at me like it's lunchtime", trad: "Les rappeurs ont faim et me regardent comme si c'était l'heure du déjeuner" },
                { t: 213.138, texte: "I know there was a time where once I was king of the underground", trad: "Je sais qu'il y a eu un temps où j'étais le roi de l'underground" },
                { t: 215.908, texte: "But I still rap like I'm on my Pharoahe Monch grind", trad: "Mais je rappe encore comme si j'étais au charbon" },
                { t: 218.079, texte: "So I crunch rhymes, but sometimes when you combine", trad: "Alors je broie des rimes, mais parfois quand tu combines" },
                { t: 220.514, texte: "Appeal with the skin color of mine", trad: "L'attrait lié à ma couleur de peau" },
                { t: 222.084, texte: "You get too big and here they come tryin'", trad: "Tu deviens trop grand et les voilà qui essaient" },
                { t: 223.776, texte: "To censor you like that one line", trad: "De te censurer comme cette ligne" },
                { t: 225.274, texte: "I said on 'I'm Back' from The Mathers LP 1 when I", trad: "Que j'ai dite dans 'I'm Back' du premier Mathers LP quand j'ai" },
                { t: 227.857, texte: "Tried to say I'll take seven kids from Columbine", trad: "Essayé de dire que je prendrais sept gamins de Columbine" },
                { t: 230.363, texte: "Put 'em all in a line, add an AK-47, a revolver and a 9", trad: "Mets-les tous en ligne, ajoute un AK-47, un revolver et un 9mm" },
                { t: 233.889, texte: "See if I get away with it now that I ain't as big as I was, but I'm", trad: "Voyons si je m'en sors maintenant que je suis moins imposant" },
                { t: 237.305, texte: "Morphin' into an immortal, comin' through the portal", trad: "Me transformant en immortel, traversant le portail" },
                { t: 239.741, texte: "You're stuck in a time warp from 2004 though", trad: "Toi tu es coincé dans une faille temporelle de 2004" },
                { t: 242.220, texte: "And I don't know what the fuck that you rhyme for", trad: "Et je ne sais pas pourquoi putain tu fais des rimes" },
                { t: 244.078, texte: "You're pointless as Rapunzel with fuckin' cornrows", trad: "Tu es aussi inutile que Raiponce avec des tresses" },
                { t: 246.793, texte: "You write normal? Fuck being normal!", trad: "Tu écris normalement ? Au diable la normalité !" },
                { t: 248.607, texte: "And I just bought a new raygun from the future", trad: "Et je viens d'acheter un pistolet laser du futur" },
                { t: 250.471, texte: "Just to come and shoot ya, like when Fabolous made Ray J mad", trad: "Juste pour te descendre, comme quand Fabolous a fâché Ray J" },
                { t: 253.158, texte: "'Cause Fab said he looked like a fag at Mayweather's pad", trad: "Parce que Fab a dit qu'il avait l'air d'un gay chez Mayweather" },
                { t: 254.741, texte: "Singin' to a man while he played piano", trad: "Chantant pour un homme pendant qu'il jouait du piano" },
                { t: 256.622, texte: "Man, oh man, that was a 24/7 special on the cable channel", trad: "C'était un spécial 24/7 sur les chaînes du câble" },
                { t: 259.708, texte: "So Ray J went straight to the radio station", trad: "Alors Ray J est allé direct à la station de radio" },
                { t: 261.570, texte: "The very next day, 'Hey Fab, I'ma kill you!'", trad: "Dès le lendemain, 'Hey Fab, je vais te tuer !'" },
                { t: 263.662, texte: "Lyrics comin' at you at supersonic speed (J.J. Fad)", trad: "Les paroles t'arrivent dessus à une vitesse supersonique" },
                { t: 265.799, texte: "Uh, summa-lumma, dooma-lumma, you assumin' I'm a human", trad: "Uh, summa-lumma, dooma-lumma, tu présumes que je suis humain" },
                { t: 267.704, texte: "What I gotta do to get it through to you I'm superhuman?", trad: "Que dois-je faire pour te faire comprendre que je suis surhumain ?" },
                { t: 269.281, texte: "Innovative and I'm made of rubber so that anything you say is ricochetin' off of me and it'll glue to you and", trad: "Innovant et fait de caoutchouc, tout ce que tu dis ricoche sur moi et se collera à toi" },
                { t: 272.605, texte: "I'm devastating, more than ever demonstrating", trad: "Je suis dévastateur, démontrant plus que jamais" },
                { t: 273.817, texte: "How to give a motherfuckin' audience a feeling like it's levitating", trad: "Comment donner au public l'impression de léviter" },
                { t: 275.772, texte: "Never fading, and I know the haters are forever waiting", trad: "Jamais démodé, et je sais que les rageux attendent" },
                { t: 277.439, texte: "For the day that they can say I fell off, they'll be celebrating", trad: "Le jour où ils pourront dire que j'ai chuté, ils fêteront ça" },
                { t: 279.026, texte: "'Cause I know the way to get 'em motivated", trad: "Parce que je sais comment les motiver" },
                { t: 280.196, texte: "I make elevating music, you make elevator music", trad: "Je fais de la musique qui élève, tu fais de la musique d'ascenseur" },
                { t: 282.581, texte: "'Oh, he's too mainstream.'", trad: "'Oh, il est trop commercial.'" },
                { t: 283.781, texte: "Well, that's what they do when they get jealous, they confuse it", trad: "C'est ce qu'ils font quand ils sont jaloux, ils s'embrouillent" },
                { t: 285.779, texte: "'It's not hip-hop, it's pop,'—'cause I found a hella way to fuse it", trad: "'C'est pas du hip-hop, c'est de la pop' car j'ai su fusionner les deux" },
                { t: 289.023, texte: "With rock, shock rap with Doc", trad: "Avec le rock, le shock rap avec Doc" },
                { t: 290.653, texte: "Throw on 'Lose Yourself' and make 'em lose it", trad: "Mets 'Lose Yourself' et fais-les craquer" },
                { t: 292.220, texte: "I don't know how to make songs like that, I don't know what words to use.", trad: "Je ne sais pas faire de chansons comme ça, je ne sais pas quels mots utiliser." },
                { t: 295.391, texte: "Let me know when it occurs to you", trad: "Préviens-moi quand ça te viendra à l'esprit" },
                { t: 296.558, texte: "While I'm rippin' any one of these verses that versus you", trad: "Pendant que je déchire n'importe lequel de ces couplets contre toi" },
                { t: 298.499, texte: "It's curtains, I'm inadvertently hurtin' you", trad: "C'est la fin, je te blesse sans le faire exprès" },
                { t: 299.980, texte: "How many verses I gotta murder to", trad: "Combien de couplets je dois massacrer pour" },
                { t: 301.903, texte: "Prove that if you were half as nice your songs you could sacrifice virgins too?", trad: "Prouver que si tu étais à moitié aussi bon tes chansons pourraient sacrifier des vierges aussi ?" },
                { t: 304.899, texte: "Ugh, school flunky, pill junkie", trad: "Ugh, cancre à l'école, accro aux cachetons" },
                { t: 307.446, texte: "But look at the accolades these skills brung me", trad: "Mais regarde les récompenses que ces talents m'ont apportées" },
                { t: 309.712, texte: "Full of myself, but still hungry", trad: "Plein de moi-même, mais j'ai encore faim" },
                { t: 311.677, texte: "I bully myself 'cause I make me do what I put my mind to", trad: "Je me brusque car je m'oblige à réussir ce que j'entreprends" },
                { t: 314.563, texte: "And I'm a million leagues above you", trad: "Et je suis à un million de lieues au-dessus de toi" },
                { t: 316.878, texte: "Ill when I speak in tongues, but it's still tongue-in-cheek, fuck you!", trad: "Génial quand je parle en langues, mais c'est ironique, va te faire !" },
                { t: 319.875, texte: "I'm drunk, so, Satan, take the fucking wheel", trad: "Je suis bourré, alors Satan, prends le volant" },
                { t: 322.076, texte: "I'ma sleep in the front seat", trad: "Je vais dormir sur le siège passager" },
                { t: 323.183, texte: "Bumpin' Heavy D and the Boyz, still 'Chunky but Funky'", trad: "Écoutant Heavy D and the Boyz, toujours 'Chunky but Funky'" },
                { t: 326.354, texte: "But in my head there's something I can feel tugging and struggling", trad: "Mais dans ma tête, je sens quelque chose qui tire et lutte" },
                { t: 329.697, texte: "Angels fight with devils, and here's what they want from me", trad: "Les anges se battent avec les démons, voici ce qu'ils veulent" },
                { t: 333.320, texte: "They're askin' me to eliminate some of the women hate", trad: "Ils me demandent d'éliminer un peu de cette haine des femmes" },
                { t: 335.179, texte: "But if you take into consideration the bitter hatred I have", trad: "Mais si tu prends en considération la haine amère que j'ai" },
                { t: 336.945, texte: "Then you may be a little patient and more sympathetic to the situation", trad: "Alors tu seras peut-être patient et plus compatissant" },
                { t: 339.989, texte: "And understand the discrimination", trad: "Et tu comprendras la discrimination" },
                { t: 342.065, texte: "But fuck it, life's handin' you lemons? Make lemonade then!", trad: "Mais merde, la vie te donne des citrons ? Fais-en de la limonade !" },
                { t: 345.169, texte: "But if I can't batter the women", trad: "Mais si je ne peux pas battre les femmes" },
                { t: 346.473, texte: "How the fuck am I supposed to bake them a cake then?", trad: "Comment suis-je censé leur cuisiner un gâteau ?" },
                { t: 348.618, texte: "Don't mistake him for Satan; it's a fatal mistake", trad: "Ne le confonds pas avec Satan, c'est une erreur fatale" },
                { t: 350.533, texte: "If you think I need to be overseas and take a vacation", trad: "Si tu penses que j'ai besoin de partir en vacances à l'étranger" },
                { t: 352.895, texte: "To trip a broad, and make her fall on her face and", trad: "Pour faire trébucher une nana et la faire tomber sur le nez" },
                { t: 355.611, texte: "Don't be a retard! Be a king? Think not", trad: "Ne sois pas stupide ! Être un roi ? Je ne pense pas" },
                { t: 358.136, texte: "Why be a king when you can be a God?", trad: "Pourquoi être un roi quand on peut être un Dieu ?" }
            ]
        }
    ],
    espagnol: [
        {
            niveau: 1,
            titre: "Limón y Sal",
            artiste: "Julieta Venegas",
            fichier: "songs/espagnol/espagnol_1.mp3",
            ambiance: "#FFD700", // Jaune Citron de base
            paroles: [
                { t: 0.0, texte: "♪ (Intro Accordéon)", trad: "♪ (Intro Accordéon)" },
                { t: 17, texte: "Tengo que confesar que a veces", trad: "Je dois avouer que parfois" },
                { t: 20.6, texte: "No me gusta tu forma de ser", trad: "Je n'aime pas ta façon d'être" },
                { t: 26, texte: "Luego te me desapareces", trad: "Puis tu disparais de ma vue" },
                { t: 29.9, texte: "Y no entiendo muy bien por qué", trad: "Et je ne comprends pas très bien pourquoi" },
                { t: 33.8, texte: "No dices nada romántico", trad: "Tu ne dis rien de romantique" },
                { t: 38, texte: "Cuando llega el atardecer", trad: "Quand vient le coucher du soleil" },
                { t: 43, texte: "Te pones de un humor extraño", trad: "Tu te mets d'une humeur étrange" },
                { t: 47, texte: "Con cada luna llena al mes", trad: "À chaque pleine lune du mois" },

                { t: 51.9, texte: "Pero a todo lo demás", trad: "Mais par-dessus tout le reste" },
                { t: 55.9, texte: "Le gana lo bueno que me das", trad: "Le bien que tu me donnes l'emporte" },
                { t: 60, texte: "Sólo tenerte cerca", trad: "Rien que de t'avoir près de moi" },
                { t: 64.8, texte: "Siento que vuelvo a empezar", trad: "Je sens que je recommence à zéro" },

                // REFRAIN
                { t: 69.2, texte: "Yo te quiero con limón y sal", trad: "Je t'aime avec du citron et du sel" },
                { t: 71.8, texte: "Yo te quiero tal y como estás", trad: "Je t'aime tel que tu es" },
                { t: 73.9, texte: "No hace falta cambiarte nada", trad: "Pas besoin de te changer" },
                { t: 77.9, texte: "Yo te quiero si vienes o si vas", trad: "Je t'aime si tu viens ou si tu pars" },
                { t: 80, texte: "Si subes y bajas y no estás", trad: "Si tu montes, si tu descends et si tu n'es pas" },
                { t: 82.8, texte: "Seguro de lo que sientes", trad: "Sûr de ce que tu ressens" },

                {t:90, text: "♪(Musica)", trad: "♪(Musique)"},

                { t: 103.9, texte: "Tengo que confesarte ahora", trad: "Je dois t'avouer maintenant" },
                { t: 107, texte: "Nunca creí en la felicidad", trad: "Que je n'ai jamais cru au bonheur" },
                { t: 112.3, texte: "A veces algo se le parece", trad: "Parfois quelque chose y ressemble" },
                { t: 116.5, texte: "Pero es pura casualidad", trad: "Mais c'est pur hasard" },

                { t: 120.9, texte: "Luego me vengo a encontrar", trad: "Puis je finis par trouver" },
                { t: 124.9, texte: "Con tus ojos me dan algo más", trad: "Dans tes yeux, quelque chose de plus" },
                { t: 129.7, texte: "Sólo tenerte cerca", trad: "Rien que de t'avoir près de moi" },
                { t: 133.9, texte: "Siento que vuelvo a empezar", trad: "Je sens que je recommence à zéro" },

                // REFRAIN 2
                { t: 138.7, texte: "Yo te quiero con limón y sal", trad: "Je t'aime avec du citron et du sel" },
                { t: 140.9, texte: "Yo te quiero tal y como estás", trad: "Je t'aime tel que tu es" },
                { t: 142.9, texte: "No hace falta cambiarte nada", trad: "Pas besoin de te changer" },
                { t: 147, texte: "Yo te quiero si vienes o si vas", trad: "Je t'aime si tu viens ou si tu pars" },
                { t: 149.8, texte: "Si subes y bajas y no estás", trad: "Si tu montes, si tu descends et si tu n'es pas" },
                { t: 151.8, texte: "Seguro de lo que sientes", trad: "Sûr de ce que tu ressens" },
                
                { t: 155.9, texte: "Yo te quiero con limón y sal", trad: "Je t'aime avec du citron et du sel" },
                { t: 157.9, texte: "Yo te quiero tal y como estás", trad: "Je t'aime tel que tu es" },
                { t: 160, texte: "No hace falta cambiarte nada", trad: "Pas besoin de te changer" },
                { t: 164.8, texte: "Yo te quiero si vienes o si vas", trad: "Je t'aime si tu viens ou si tu pars" },
                { t: 166.9, texte: "Si subes y bajas y no estás", trad: "Si tu montes, si tu descends et si tu n'es pas" },
                { t: 168.9, texte: "Seguro de lo que sientes", trad: "Sûr de ce que tu ressens" },

                {t: 175, texte: "♪(Musica)", trad: "♪(Musique)"},

                { t: 189.9, texte: "Sólo tenerte cerca", trad: "Rien que de t'avoir près de moi" },
                { t: 194.1, texte: "Siento que vuelvo a empezar", trad: "Je sens que je recommence à zéro" }
            ]
        }
    ],
    italien: [
        {
            niveau: 1,
            titre: "L'italiano",
            artiste: "Toto Cutugno",
            fichier: "songs/italien/italien_1.mp3",
            ambiance: "linear-gradient(135deg, #008C45 0%, #F4F5F0 50%, #CD212A 100%)", // Vert, Blanc, Rouge
            paroles: [
                { t: 1, texte: "Lasciatemi cantare", trad: "Laissez-moi chanter" },
                { t: 5.5, texte: "Con la chitarra in mano", trad: "La guitare à la main" },
                { t: 9.8, texte: "Lasciatemi cantare", trad: "Laissez-moi chanter" },
                { t: 13.3, texte: "Sono un italiano", trad: "Je suis un italien" },

                { t: 18.9, texte: "Buongiorno Italia gli spaghetti al dente", trad: "Bonjour l'Italie, les spaghetti al dente" },
                { t: 22.8, texte: "E un partigiano come presidente", trad: "Et un partisan comme président" },
                { t: 26, texte: "Con l'autoradio sempre nella mano destra", trad: "Avec l'autoradio toujours dans la main droite" },
                { t: 29.9, texte: "E un canarino sopra la finestra", trad: "Et un canari sur la fenêtre" },

                { t: 34.8, texte: "Buongiorno Italia con i tuoi artisti", trad: "Bonjour l'Italie avec tes artistes" },
                { t: 38.7, texte: "Con troppa America sui manifesti", trad: "Avec trop d'Amérique sur les affiches" },
                { t: 41.9, texte: "Con le canzoni con amore", trad: "Avec les chansons avec amour" },
                { t: 44.8, texte: "Con il cuore", trad: "Avec le cœur" },
                { t: 45.7, texte: "Con più donne e sempre meno suore", trad: "Avec plus de femmes et toujours moins de nonnes" },

                { t: 50, texte: "Buongiorno Italia", trad: "Bonjour l'Italie" },
                { t: 51.4, texte: "Buongiorno Maria", trad: "Bonjour Marie" },
                { t: 54, texte: "Con gli occhi pieni di malinconia", trad: "Avec les yeux pleins de mélancolie" },
                { t: 57.9, texte: "Buongiorno Dio", trad: "Bonjour Dieu" },
                { t: 61, texte: "Lo sai che ci sono anch'io", trad: "Tu sais que je suis là moi aussi" },

                // REFRAIN
                { t: 64.9, texte: "Lasciatemi cantare", trad: "Laissez-moi chanter" },
                { t: 68.9, texte: "Con la chitarra in mano", trad: "La guitare à la main" },
                { t: 72.9, texte: "Lasciatemi cantare", trad: "Laissez-moi chanter" },
                { t: 75.9, texte: "Una canzone piano piano", trad: "Une chanson tout doucement" },
                { t: 80.9, texte: "Lasciatemi cantare", trad: "Laissez-moi chanter" },
                { t: 84.9, texte: "Perché ne sono fiero", trad: "Parce que j'en suis fier" },
                { t: 88.8, texte: "Sono un italiano", trad: "Je suis un italien" },
                { t: 92.5, texte: "Un italiano vero", trad: "Un vrai italien" },

                { t: 97.8, texte: "Buongiorno Italia che non si spaventa", trad: "Bonjour l'Italie qui n'a pas peur" },
                { t: 101.9, texte: "Con la crema da barba alla menta", trad: "Avec la crème à raser à la menthe" },
                { t: 104.9, texte: "Con un vestito gessato sul blu", trad: "Avec un costume à rayures bleu" },
                { t: 108.7, texte: "E la moviola la domenica in TV", trad: "Et le ralenti le dimanche à la télé" },

                { t: 113.8, texte: "Buongiorno Italia col caffè ristretto", trad: "Bonjour l'Italie avec le café serré" },
                { t: 117.9, texte: "Le calze nuove nel primo cassetto", trad: "Les chaussettes neuves dans le premier tiroir" },
                { t: 121.9, texte: "Con la bandiera in tintoria", trad: "Avec le drapeau au pressing" },
                { t: 123.9, texte: "E una Seicento giù di carrozzeria", trad: "Et une Fiat 600 cabossée" },

                { t: 129.9, texte: "Buongiorno Italia", trad: "Bonjour l'Italie" },
                { t: 130.9, texte: "Buongiorno Maria", trad: "Bonjour Marie" },
                { t: 133.9, texte: "Con gli occhi pieni di malinconia", trad: "Avec les yeux pleins de mélancolie" },
                { t: 136.9, texte: "Buongiorno Dio", trad: "Bonjour Dieu" },
                { t: 140.7, texte: "Lo sai che ci sono anch'io", trad: "Tu sais que je suis là moi aussi" },

                // REFRAIN FINAL
                { t: 144, texte: "Lasciatemi cantare", trad: "Laissez-moi chanter" },
                { t: 148, texte: "Con la chitarra in mano", trad: "La guitare à la main" },
                { t: 152, texte: "Lasciatemi cantare", trad: "Laissez-moi chanter" },
                { t: 154.9, texte: "Una canzone piano piano", trad: "Une chanson tout doucement" },
                { t: 160, texte: "Lasciatemi cantare", trad: "Laissez-moi chanter" },
                { t: 164, texte: "Perché ne sono fiero", trad: "Parce que j'en suis fier" },
                { t: 168, texte: "Sono un italiano", trad: "Je suis un italien" },
                { t: 172, texte: "Un italiano vero", trad: "Un vrai italien" },
                
                { t: 179.5, texte: "♪ (La la la...)", trad: "♪ (La la la...)" },

                { t: 194.9, texte: "Lasciatemi cantare", trad: "Laissez-moi chanter" },
                { t: 198.9, texte: "Con la chitarra in mano", trad: "La guitare à la main" },
                { t: 202.9, texte: "Lasciatemi cantare", trad: "Laissez-moi chanter" },
                { t: 205.7, texte: "Una canzone piano piano", trad: "Une chanson tout doucement" },
                { t: 210.6, texte: "Lasciatemi cantare", trad: "Laissez-moi chanter" },
                { t: 215.6, texte: "Perché ne sono fiero", trad: "Parce que j'en suis fier" },
                { t: 219.7, texte: "Sono un italiano", trad: "Je suis un italien" },
                { t: 225, texte: "Un italiano vero", trad: "Un vrai italien" },
            ]
        }
    ],
    allemand: [
        {
            niveau: 1,
            titre: "99 Luftballons",
            artiste: "Nena",
            fichier: "songs/allemand/allemand_1.mp3",
            ambiance: "linear-gradient(135deg, #000000 0%, #FF0000 50%, #FFCC00 100%)",
            paroles: [
                { t: 3.5, texte: "Hast du etwas Zeit für mich?", trad: "As-tu un peu de temps pour moi ?" },
                { t: 6.8, texte: "Dann singe ich ein Lied für dich", trad: "Alors je chanterai une chanson pour toi" },
                { t: 9.7, texte: "Von neunundneunzig Luftballons", trad: "De 99 ballons" },
                { t: 13.1, texte: "Auf ihrem Weg zum Horizont", trad: "Sur leur chemin vers l'horizon" },
                { t: 16.7, texte: "Denkst du vielleicht grad' an mich?", trad: "Penses-tu peut-être à moi en ce moment ?" },
                { t: 20.0, texte: "Dann singe ich ein Lied für dich", trad: "Alors je chanterai une chanson pour toi" },
                { t: 22.7, texte: "Von neunundneunzig Luftballons", trad: "De 99 ballons" },
                { t: 26.5, texte: "Und dass sowas von sowas kommt", trad: "Et comment de telles choses arrivent" },
                
                { t: 31.6, texte: "♪ Musique", trad: "♪ Musique" },

                { t: 71.3, texte: "Neunundneunzig Luftballons", trad: "99 ballons" },
                { t: 73.7, texte: "Auf ihrem Weg zum Horizont", trad: "Sur leur chemin vers l'horizon" },
                { t: 76.1, texte: "Hielt man für UFOs aus dem All", trad: "On les a pris pour des OVNI de l'espace" },
                { t: 78.6, texte: "Darum schickte ein General", trad: "C'est pourquoi un général envoya" },
                { t: 81.4, texte: "'ne Fliegerstaffel hinterher", trad: "Une escadrille d'avions à leur poursuite" },
                { t: 83.9, texte: "Alarm zu geben, wenn's so wär", trad: "Pour donner l'alerte si c'était le cas" },
                { t: 86.4, texte: "Dabei war'n da am Horizont", trad: "Pourtant, il n'y avait là à l'horizon" },
                { t: 89.1, texte: "Nur neunundneunzig Luftballons", trad: "Que 99 ballons" },

                { t: 92.1, texte: "♪ Musique", trad: "♪ Musique" },

                { t: 101.8, texte: "Neunundneunzig Düsenflieger", trad: "99 avions de chasse" },
                { t: 104.0, texte: "Jeder war ein großer Krieger", trad: "Chacun était un grand guerrier" },
                { t: 107.0, texte: "Hielten sich für Captain Kirk", trad: "Se prenaient pour le Capitaine Kirk" },
                { t: 108.8, texte: "Das gab ein großes Feuerwerk", trad: "Ça a donné un grand feu d'artifice" },
                { t: 111.8, texte: "Die Nachbarn haben nichts gerafft", trad: "Les voisins n'ont rien compris" },
                { t: 114.3, texte: "Und fühlten sich gleich angemacht", trad: "Et se sont sentis provoqués" },
                { t: 116.8, texte: "Dabei schoss man am Horizont", trad: "Alors on a tiré à l'horizon" },
                { t: 119.0, texte: "Auf neunundneunzig Luftballons", trad: "Sur 99 ballons" },

                { t: 121.9, texte: "♪ Musique (Solo)", trad: "♪ Musique (Solo)" },

                { t: 152.2, texte: "Neunundneunzig Kriegsminister", trad: "99 ministres de la guerre" },
                { t: 154.6, texte: "Streichholz und Benzinkanister", trad: "Allumettes et bidons d'essence" },
                { t: 157.1, texte: "Hielten sich für schlaue Leute", trad: "Se croyaient être des gens malins" },
                { t: 159.5, texte: "Witterten schon fette Beute", trad: "Flairaient déjà un gros butin" },
                { t: 162.1, texte: "Riefen: Krieg und wollten Macht", trad: "Criaient : Guerre et voulaient le pouvoir" },
                { t: 164.7, texte: "Mann, wer hätte das gedacht", trad: "Mince, qui l'aurait cru" },
                { t: 167.3, texte: "Dass es einmal soweit kommt", trad: "Qu'on en arriverait là un jour" },
                { t: 169.8, texte: "Wegen neunundneunzig Luftballons", trad: "À cause de 99 ballons" },
                
                { t: 174.9, texte: "Wegen neunundneunzig Luftballons", trad: "À cause de 99 ballons" },
                { t: 177.8, texte: "♪ Musique", trad: "♪ Musique" },
                { t: 185.2, texte: "Neunundneunzig Luftballons", trad: "99 ballons" },
                { t: 187.6, texte: "♪ Musique", trad: "♪ Musique" },

                { t: 196.2, texte: "Neunundneunzig Jahre Krieg", trad: "99 ans de guerre" },
                { t: 199.4, texte: "Ließen keinen Platz für Sieger", trad: "N'ont laissé aucune place aux vainqueurs" },
                { t: 202.8, texte: "Kriegsminister gibt's nicht mehr", trad: "Il n'y a plus de ministres de la guerre" },
                { t: 206.1, texte: "Und auch aucune Düsenflieger", trad: "Et plus d'avions de chasse non plus" },
                { t: 209.3, texte: "Heute zieh' ich meine Runden", trad: "Aujourd'hui je fais mon tour" },
                { t: 212.9, texte: "Seh' die Welt in Trümmern liegen", trad: "Je vois le monde en ruines" },
                { t: 216.3, texte: "Hab' 'nen Luftballon gefunden", trad: "J'ai trouvé un ballon" },
                { t: 220.6, texte: "Denk' an dich und lass' ihn fliegen", trad: "Je pense à toi et je le laisse s'envoler" }
            ]
        }
    ],
    arabe: [
        {
            niveau: 1,
            titre: "Sana Helwa Ya Gamil",
            artiste: "Traditionnel",
            fichier: "songs/arabe/arabe_1.mp3",
            ambiance: "linear-gradient(135deg, #bf953f, #fcf6ba, #b38728",
            paroles: [
                { t: 2.1, texte: "سنة حلوة يا جميل", trad: "Joyeux anniversaire, ô toi le beau" },
                { t: 5.0, texte: "سنة حلوة يا جميل", trad: "Joyeux anniversaire, ô toi le beau" },
                { t: 8.5, texte: "سنة حلوة، سنة حلوة", trad: "Bonne année, bonne année" },
                { t: 12.0, texte: "سنة حلوة يا جميل", trad: "Joyeux anniversaire, ô toi le beau" },
                
                { t: 14.7, texte: "♪ Musique", trad: "♪ Musique" },

                { t: 15.8, texte: "سنة حلوة يا جميل", trad: "Joyeux anniversaire, ô toi le beau" },
                { t: 19.0, texte: "سنة حلوة يا جميل", trad: "Joyeux anniversaire, ô toi le beau" },
                { t: 22.5, texte: "سنة حلوة، سنة حلوة", trad: "Bonne année, bonne année" },
                { t: 26.2, texte: "سنة حلوة يا جميل", trad: "Joyeux anniversaire, ô toi le beau" }
            ]
        }
    ],
    russe: [
        {
            niveau: 1,
            titre: "Katioucha (Катюша)",
            artiste: "Valeria Kurnushkina",
            fichier: "songs/russe/russe_1.mp3",
            ambiance: "linear-gradient(135deg, #134e5e 0%, #71b280 100%)",
            paroles: [
                { t: 0.0, texte: "♪ Discours d'introduction", trad: "♪ Présentation de l'artiste" },
                { t: 15.0, texte: "♪ Musique", trad: "♪ Musique" },

                { t: 23.5, texte: "Расцветали яблони и груши", phon: "Rastsvetali yabloni i grushi", trad: "Les pommiers et les poiriers fleurissaient" },
                { t: 27.8, texte: "Поплыли туманы над рекой", phon: "Poplyli tumany nad rekoy", trad: "Les brumes flottaient sur la rivière" },
                { t: 31.6, texte: "Выходила на берег Катюша", phon: "Vykhodila na bereg Katyusha", trad: "Katioucha s'en alla sur la rive" },
                { t: 35.8, texte: "На высокий берег на крутой", phon: "Na vysokiy bereg na krutoy", trad: "Sur la rive haute et escarpée" },
                { t: 39.9, texte: "Выходила на берег Катюша", phon: "Vykhodila na bereg Katyusha", trad: "Katioucha s'en alla sur la rive" },
                { t: 43.3, texte: "На высокий берег на крутой", phon: "Na vysokiy bereg na krutoy", trad: "Sur la rive haute et escarpée" },

                { t: 47.1, texte: "Выходила, песню заводила", phon: "Vykhodila, pesnyu zavodila", trad: "Elle s'en alla en chantant une chanson" },
                { t: 50.9, texte: "Про степного, сизого орла", phon: "Pro stepnogo, sizogo orla", trad: "À propos de l'aigle gris de la steppe" },
                { t: 54.7, texte: "Про того, которого любила", phon: "Pro togo, kotorogo lyubila", trad: "À propos de celui qu'elle aimait" },
                { t: 58.9, texte: "Про того, чьи письма берегла", phon: "Pro togo, ch'i pis'ma beregla", trad: "À propos de celui dont elle gardait les lettres" },
                { t: 62.3, texte: "Про того, которого любила", phon: "Pro togo, kotorogo lyubila", trad: "À propos de celui qu'elle aimait" },
                { t: 66.4, texte: "Про того, чьи письма берегла", phon: "Pro togo, ch'i pis'ma beregla", trad: "À propos de celui dont elle gardait les lettres" },

                { t: 69.3, texte: "♪ Musique", trad: "♪ Musique" },

                { t: 77.6, texte: "Ой, ты, песня, песенка девичья", phon: "Oy, ty, pesnya, pesenka devich'ya", trad: "Oh, toi, chanson, chanson d'une jeune fille" },
                { t: 81.5, texte: "Ты лети за ясным солнцем вслед", phon: "Ty leti za yasnym solntsem vsled", trad: "Vole vers le soleil radieux" },
                { t: 85.2, texte: "И бойцу на дальнем пограничье", phon: "I boytsu na dal'nem pogranich'ye", trad: "Et au soldat sur la frontière lointaine" },
                { t: 89.4, texte: "От Катюши передай привет", phon: "Ot Katyushi pereday privet", trad: "Transmets le bonjour de Katioucha" },
                { t: 93.0, texte: "И бойцу на дальнем пограничье", phon: "I boytsu na dal'nem pogranich'ye", trad: "Et au soldat sur la frontière lointaine" },
                { t: 96.9, texte: "От Катюши передай привет", phon: "Ot Katyushi pereday privet", trad: "Transmets le bonjour de Katioucha" },

                { t: 100.8, texte: "Пусть он вспомнит девушку простую", phon: "Pust' on vspomnit devushku prostuyu", trad: "Qu'il se souvienne d'une simple jeune fille" },
                { t: 104.3, texte: "Пусть услышит, как она поет", phon: "Pust' uslyshit, kak ona poyet", trad: "Qu'il l'entende chanter" },
                { t: 107.9, texte: "Пусть он землю бережет родную", phon: "Pust' on zemlyu berezhet rodnuyu", trad: "Qu'il protège sa terre natale" },
                { t: 111.8, texte: "А любовь Катюша сбережет", phon: "A lyubov' Katyusha sberezhët", trad: "Et Katioucha préservera leur amour" },
                { t: 115.5, texte: "Пусть он землю бережет родную", phon: "Pust' on zemlyu berezhet rodnuyu", trad: "Qu'il protège sa terre natale" },
                { t: 119.6, texte: "А любовь Катюша сбережет", phon: "A lyubov' Katyusha sberezhët", trad: "Et Katioucha préservera leur amour" },

                { t: 123.1, texte: "♪ Musique", trad: "♪ Musique" },

                { t: 130.6, texte: "Расцветали яблони и груши", phon: "Rastsvetali yabloni i grushi", trad: "Les pommiers et les poiriers fleurissaient" },
                { t: 134.3, texte: "Поплыли туманы над рекой", phon: "Poplyli tumany nad rekoy", trad: "Les brumes flottaient sur la rivière" },
                { t: 138.1, texte: "Выходила на берег Катюша", phon: "Vykhodila na bereg Katyusha", trad: "Katioucha s'en alla sur la rive" },
                { t: 142.1, texte: "На высокий берег на крутой", phon: "Na vysokiy bereg na krutoy", trad: "Sur la rive haute et escarpée" },
                { t: 145.7, texte: "Выходила на берег Катюша", phon: "Vykhodila na bereg Katyusha", trad: "Katioucha s'en alla sur la rive" },
                { t: 149.9, texte: "На высокий берег на крутой", phon: "Na vysokiy bereg na krutoy", trad: "Sur la rive haute et escarpée" },
                { t: 153.0, texte: "♪ Applaudissements", trad: "♪ Applaudissements" }
            ]
        }
    ],
    grec: [
        {
            niveau: 1,
            titre: "S'Agapo (Σ' αγαπώ)",
            artiste: "Giorgos Dalaras",
            fichier: "songs/grec/grec_1.mp3",
            ambiance: "linear-gradient(135deg, #2c3e50 0%, #bdc3c7 100%)",
            paroles: [
                { t: 0.2, texte: "♪ Musique", trad: "♪ Musique" },
                
                { t: 32.1, texte: "Σ’ αγαπώ", trad: "Je t'aime" },
                { t: 37.4, texte: "Σ’ αγαπώ γιατί είσαι ωραία", trad: "Je t'aime parce que tu es belle" },
                { t: 46.1, texte: "Σ’ αγαπώ γιατί είσαι ωραία", trad: "Je t'aime parce que tu es belle" },
                { t: 52.4, texte: "Σ’ αγαπώ γιατί είσαι εσύ", trad: "Je t'aime parce que c'est toi" },

                { t: 60.8, texte: "Αγαπώ", trad: "J'aime" },
                { t: 106.5, texte: "Αγαπώ κι όλο τον κόσμο", trad: "J'aime aussi le monde entier" },
                { t: 114.7, texte: "Αγαπώ κι όλο τον κόσμο", trad: "J'aime aussi le monde entier" },
                { t: 120.4, texte: "Γιατί ζεις κι εσύ μαζί", trad: "Parce que tu y vis toi aussi" },

                { t: 155.2, texte: "Το παρα-", trad: "La fenê-" },
                { t: 200.6, texte: "Το παράθυρο κλεισμένο", trad: "La fenêtre fermée" },
                { t: 209.5, texte: "Το παράθυρο κλεισμένο", trad: "La fenêtre fermée" },
                { t: 215.6, texte: "Το πα-", trad: "La fe-" },

                { t: 224.3, texte: "Άνοιξε", trad: "Ouvre" },
                { t: 229.9, texte: "Άνοιξε το ένα φύλλο", trad: "Ouvre un volet" },
                { t: 238.6, texte: "Άνοιξε το ένα φύλλο", trad: "Ouvre un volet" },
                { t: 245.3, texte: "Την εικόνα σου να δω", trad: "Pour que je voie ton image" },

                { t: 253.8, texte: "♪ Longue partie instrumentale", trad: "♪ Longue partie instrumentale" },

                { t: 320.0, texte: "Σ’ αγαπώ", trad: "Je t'aime" },
                { t: 325.8, texte: "Σ’ αγαπώ γιατί είσαι ωραία", trad: "Je t'aime parce que tu es belle" },
                { t: 335.0, texte: "Σ’ αγαπώ γιατί είσαι ωραία", trad: "Je t'aime parce que tu es belle" },
                { t: 341.1, texte: "Σ’ αγαπώ γιατί είσαι εσύ", trad: "Je t'aime parce que c'est toi" }
            ]
        }
    ],
    hindi: [
        {
            niveau: 1,
            titre: "Tum Hi Ho",
            artiste: "Arijit Singh",
            fichier: "songs/hindi/hindi_1.mp3",
            ambiance: "linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)",
            paroles: [
                { t: 0, texte: "♪ Musique", trad: "♪ Musique" },
                { t: 10.6, texte: "हम तेरे बिन अब रह नहीं सकते", trad: "Je ne peux plus vivre sans toi" },
                { t: 15.6, texte: "तेरे बिना क्या वजूद मेरा", trad: "Sans toi, quelle est mon existence ?" },
                { t: 26.0, texte: "हम तेरे बिन अब रह नहीं सकते", trad: "Je ne peux plus vivre sans toi" },
                { t: 30.9, texte: "तेरे बिना क्या वजूद मेरा", trad: "Sans toi, quelle est mon existence ?" },
                { t: 35.8, texte: "तुझसे जुदा गर हो जायेंगे", trad: "Si jamais je devais être séparé de toi" },
                { t: 41.9, texte: "तो खुद से ही हो जायेंगे जुदा", trad: "Alors je serais séparé de moi-même" },
                { t: 48.7, texte: "क्यूँकि तुम ही हो", trad: "Parce que c'est toi" },
                { t: 51.2, texte: "अब तुम ही हो", trad: "Maintenant, c'est seulement toi" },
                { t: 54.0, texte: "ज़िंदगी अब तुम ही हो", trad: "Ma vie désormais, c'est toi" },
                { t: 59.0, texte: "चैन भी, मेरा दर्द भी", trad: "Ma paix, et ma douleur aussi" },
                { t: 64.0, texte: "मेरी आशिकी अब तुम ही हो", trad: "Mon amour désormais, c'est toi" },
                {t:70, texte: "♪ Musique", trad: "♪ Musique" },
                { t: 89.9, texte: "तेरा मेरा रिश्ता है कैसा", trad: "Quelle est la nature de notre relation ?" },
                { t: 94.8, texte: "इक पल दूर गवारा नहीं", trad: "Je ne supporte pas d'être loin une seule seconde" },
                { t: 100.1, texte: "तेरे लिए हर रोज़ है जीते", trad: "Chaque jour je vis pour toi" },
                { t: 104.9, texte: "तुझ को दिया मेरा वक्त सभी", trad: "Je t'ai donné tout mon temps" },
                { t: 109.8, texte: "कोई लम्हा मेरा ना हो तेरे बिना", trad: "Qu'aucun de mes moments ne soit sans toi" },
                { t: 114.5, texte: "हर सांस पे नाम तेरा", trad: "Ton nom est sur chacune de mes respirations" },

                { t: 122.6, texte: "क्यूँकि तुम ही हो", trad: "Parce que c'est toi" },
                { t: 125.1, texte: "अब तुम ही हो", trad: "Maintenant, c'est seulement toi" },
                { t: 127.7, texte: "ज़िंदगी अब तुम ही हो", trad: "Ma vie désormais, c'est toi" },
                { t: 133.0, texte: "चैन भी, मेरा दर्द भी", trad: "Ma paix, et ma douleur aussi" },
                { t: 137.8, texte: "मेरी आशिकी अब तुम ही हो", trad: "Mon amour désormais, c'est toi" },
                {t: 144, texte: "♪ Musique", trad: "♪ Musique" },
                { t: 173.2, texte: "तेरे लिए ही जिया मैं", trad: "Je n'ai vécu que pour toi" },
                { t: 178.3, texte: "खुद को जो यूँ दे दिया है", trad: "Maintenant que je me suis donné ainsi" },
                { t: 183.3, texte: "तेरी वफ़ा ने मुझको संभाला", trad: "Ta loyauté m'a soutenu" },
                { t: 188.4, texte: "सारे ग़मों को दिल से निकाला", trad: "Elle a chassé toutes les tristesses de mon cœur" },
                { t: 194.0, texte: "तेरे साथ मेरा है नसीब जुड़ा", trad: "Mon destin est lié au tien" },
                { t: 199.1, texte: "तुझे पाके अधूरा ना रहा", trad: "En t'ayant, je ne suis plus incomplet" },

                { t: 206.8, texte: "क्यूँकि तुम ही हो", trad: "Parce que c'est toi" },
                { t: 209.3, texte: "अब तुम ही हो", trad: "Maintenant, c'est seulement toi" },
                { t: 212.2, texte: "ज़िंदगी अब तुम ही हो", trad: "Ma vie désormais, c'est toi" },
                { t: 217.3, texte: "चैन भी, मेरा दर्द भी", trad: "Ma paix, et ma douleur aussi" },
                { t: 222.5, texte: "मेरी आशिकी अब तुम ही हो", trad: "Mon amour désormais, c'est toi" },

                { t: 227.4, texte: "क्यूँकि तुम ही हो", trad: "Parce que c'est toi" },
                { t: 229.9, texte: "अब तुम ही हो", trad: "Maintenant, c'est seulement toi" },
                { t: 232.4, texte: "ज़िंदगी अब तुम ही हो", trad: "Ma vie désormais, c'est toi" },
                { t: 237.6, texte: "चैन भी, मेरा दर्द भी", trad: "Ma paix, et ma douleur aussi" },
                { t: 242.6, texte: "मेरी आशिकी अब तुम ही हो", trad: "Mon amour désormais, c'est toi" },
                
                { t: 250.6, texte: "♪ Musique", trad: "♪ Musique" }
            ]
        }
    ],
    basque: [
        {
            niveau: 1,
            titre: "Hegoak (Txoria Txori)",
            artiste: "Anne Etchegoyen & Le Chœur Aizkoa",
            fichier: "songs/basque/basque_1.mp3",
            ambiance: "linear-gradient(135deg, #1e272e 0%, #485460 50%, #d2dae2 100%)",
            paroles: [
                { t: 0.0, texte: "♪ Silence", trad: "♪ Silence" },
                { t: 10.5, texte: "♪ Musique", trad: "♪ Musique" },
                { t: 34.0, texte: "♪ la la la - la la", trad: "♪ la la la - la la" },

                { t: 51.8, texte: "Hegoak ebaki banizkio", trad: "Si je lui avais coupé les ailes" },
                { t: 55.7, texte: "Nerea izango zen", trad: "Il aurait été à moi" },
                { t: 59.5, texte: "Hegoak ebaki banizkio", trad: "Si je lui avais coupé les ailes" },
                { t: 63.5, texte: "Nerea izango zen", trad: "Il aurait été à moi" },
                { t: 67.5, texte: "Ez zuen alde egingo", trad: "Il ne se serait pas échappé" },

                { t: 71.8, texte: "Bainan, horrela", trad: "Mais, de cette façon" },
                { t: 75.1, texte: "Ez zen gehiago txoria izango", trad: "Il n'aurait plus été un oiseau" },
                { t: 80.2, texte: "Bainan, horrela", trad: "Mais, de cette façon" },
                { t: 83.7, texte: "Ez zen gehiago txoria izango", trad: "Il n'aurait plus été un oiseau" },

                { t: 86.9, texte: "Eta nik... txoria nuen maite", trad: "Et moi... c'est l'oiseau que j'aimais" },
                { t: 92.9, texte: "Eta nik... txoria nuen maite", trad: "Et moi... c'est l'oiseau que j'aimais" },

                { t: 97.6, texte: "♪ la la la - la la", trad: "♪ la la la - la la" },

                { t: 113.3, texte: "Bainan, horrela", trad: "Mais, de cette façon" },
                { t: 116.5, texte: "Ez zen gehiago txoria izango", trad: "Il n'aurait plus été un oiseau" },
                { t: 121.9, texte: "Bainan, horrela", trad: "Mais, de cette façon" },
                { t: 125.4, texte: "Ez zen gehiago txoria izango", trad: "Il n'aurait plus été un oiseau" },

                { t: 128.6, texte: "Eta nik... txoria nuen maite", trad: "Et moi... c'est l'oiseau que j'aimais" },
                { t: 134.7, texte: "Eta nik... txoria nuen maite", trad: "Et moi... c'est l'oiseau que j'aimais" },

                { t: 142.3, texte: "♪ la la la - la la", trad: "♪ la la la - la la" }
            ]
        }
    ],
    chinois: [
        {
            niveau: 1,
            titre: "The Moon Represents My Heart",
            artiste: "Teresa Teng",
            fichier: "songs/chinois/chinois_1.mp3",
            ambiance: "linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)",
            paroles: [
                { t: 0.0, texte: "♪ Silence", trad: "♪ Silence" },
                { t: 10.0, texte: "♪ Musique", trad: "♪ Musique" },

                { t: 25.0, texte: "你问我爱你有多深", trad: "Tu me demandes si mon amour est profond" },
                { t: 31.0, texte: "我爱你有几分", trad: "À quel point je t'aime" },
                { t: 36.8, texte: "我的情也真", trad: "Mes sentiments sont vrais" },
                { t: 39.8, texte: "我的爱也真", trad: "Mon amour est vrai" },
                { t: 43.0, texte: "月亮代表我的心", trad: "La lune représente mon cœur" },

                { t: 49.6, texte: "你问我爱你有多深", trad: "Tu me demandes si mon amour est profond" },
                { t: 55.5, texte: "我爱你有几分", trad: "À quel point je t'aime" },
                { t: 61.5, texte: "我的情不移", trad: "Mes sentiments ne faibliront pas" },
                { t: 64.3, texte: "我的爱不变", trad: "Mon amour ne changera pas" },
                { t: 67.5, texte: "月亮代表我的心", trad: "La lune représente mon cœur" },

                { t: 73.7, texte: "轻轻的一个吻", trad: "Un doux baiser" },
                { t: 79.7, texte: "已经打动我的心", trad: "A déjà fait vibrer mon cœur" },
                { t: 85.8, texte: "深深的一段情", trad: "Une profonde affection" },
                { t: 92.1, texte: "教我思念到如今", trad: "Me fait languir jusqu'à aujourd'hui" },

                { t: 98.9, texte: "你问我爱你有多深", trad: "Tu me demandes si mon amour est profond" },
                { t: 104.6, texte: "我爱你有几分", trad: "À quel point je t'aime" },
                { t: 110.5, texte: "我的情也真", trad: "Mes sentiments sont vrais" },
                { t: 113.4, texte: "我的爱也真", trad: "Mon amour est vrai" },
                { t: 116.7, texte: "月亮代表我的心", trad: "La lune représente mon cœur" },

                { t: 121.6, texte: "♪ Musique", trad: "♪ Musique" },

                { t: 147.3, texte: "轻轻的一个吻", trad: "Un doux baiser" },
                { t: 153.2, texte: "已经打动我的心", trad: "A déjà fait vibrer mon cœur" },
                { t: 159.4, texte: "深深的一段情", trad: "Une profonde affection" },
                { t: 165.5, texte: "教我思念到如今", trad: "Me fait languir jusqu'à aujourd'hui" },

                { t: 172.0, texte: "你问我爱你有多深", trad: "Tu me demandes si mon amour est profond" },
                { t: 178.1, texte: "我爱你有几分", trad: "À quel point je t'aime" },
                { t: 184.0, texte: "我的情也真", trad: "Mes sentiments sont vrais" },
                { t: 187.2, texte: "我的爱也真", trad: "Mon amour est vrai" },
                { t: 190.0, texte: "月亮代表我的心", trad: "La lune représente mon cœur" },

                { t: 196.0, texte: "我的情不移", trad: "Mes sentiments ne faibliront pas" },
                { t: 199.1, texte: "我的爱不变", trad: "Mon amour ne changera pas" },
                { t: 202.0, texte: "月亮代表我的心", trad: "La lune représente mon cœur" },
                { t: 216.6, texte: "♪ Silence", trad: "♪ Silence" }
            ]
        }
    ],
    coreen: [
        {
            niveau: 1,
            titre: "Eyes, Nose, Lips (눈, 코, 입)",
            artiste: "TAEYANG",
            fichier: "songs/coreen/coreen_1.mp3",
            ambiance: "linear-gradient(135deg, #000000 0%, #434343 50%, #6e1414 100%)",
            paroles: [
                { t: 0.0, texte: "♪ Silence", trad: "♪ Silence" },
                { t: 7.3, texte: "미안해 미안해 하지마", trad: "Ne dis pas que tu es désolée" },
                { t: 14.8, texte: "내가 초라해지잖아", trad: "Car cela me rend pitoyable" },
                { t: 21.6, texte: "빨간 예쁜 입술로", trad: "Avec tes jolies lèvres rouges" },
                { t: 28.5, texte: "어서 나를 죽이고 가", trad: "S'il te plaît, tue-moi et pars" },
                { t: 34.6, texte: "나는 괜찮아", trad: "Je vais bien" },
                { t: 40.2, texte: "마지막으로 나를 바라봐줘", trad: "Regarde-moi une dernière fois" },
                { t: 43.1, texte: "아무렇지 않은 듯 웃어줘", trad: "Souris-moi comme si de rien n'était" },
                { t: 49.6, texte: "네가 보고 싶을 때", trad: "Quand tu me manqueras" },
                { t: 56.5, texte: "기억할 수 있게", trad: "Pour que je puisse m'en souvenir" },
                { t: 59.8, texte: "나의 머릿속에 네 얼굴 그릴 수 있게", trad: "Pour que je puisse dessiner ton visage dans ma tête" },
                { t: 63.3, texte: "너의 눈 코 입", trad: "Tes yeux, ton nez, tes lèvres" },
                { t: 71.5, texte: "날 만지던 네 손길", trad: "Tes mains qui me touchaient" },
                { t: 78.2, texte: "작은 손톱까지 다", trad: "Jusqu'à tes petits ongles" },
                { t: 85.3, texte: "여전히 난 느낄 수 있지만", trad: "Je peux encore tout ressentir" },
                { t: 92.2, texte: "꺼진 불꽃처럼", trad: "Comme une flamme qui s'éteint" },
                { t: 99.1, texte: "타들어간 우리 사랑", trad: "Notre amour s'est consumé" },
                { t: 105.8, texte: "모두 다 너무 아프지만", trad: "Tout cela fait tellement mal" },
                { t: 112.7, texte: "이젠 널 추억이라 부를게", trad: "Mais maintenant, je t'appellerai 'un souvenir'" },
                { t: 119.5, texte: "♪ Musique", trad: "♪ Musique" },
                { t: 153.8, texte: "사랑해 사랑했지만", trad: "Je t'aime, je t'ai aimée" },
                { t: 160.7, texte: "내가 부족했었나 봐", trad: "J'imagine que je n'étais pas assez bien" },
                { t: 167.4, texte: "혹시 우연이라도", trad: "Si jamais par hasard" },
                { t: 173.8, texte: "한 번만이라도 널 볼 수 있다면", trad: "Je pouvais te voir, juste une fois" },
                { t: 179.9, texte: "내 모든 걸 다 잃어도 괜찮아", trad: "Je pourrais tout perdre, ça m'irait" },
                { t: 182.5, texte: "꿈속에서라도 너를", trad: "Même si c'est seulement dans mes rêves" },
                { t: 188.8, texte: "다시 사랑하고 싶어", trad: "Je veux t'aimer à nouveau" },
                { t: 195.4, texte: "우리 사랑했던", trad: "De notre amour" },
                { t: 198.9, texte: "그때로 나를 데려가 줘요", trad: "Ramène-moi à cette époque" },
                { t: 204.0, texte: "너의 눈 코 입", trad: "Tes yeux, ton nez, tes lèvres" },
                { t: 210.8, texte: "날 만지던 네 손길", trad: "Tes mains qui me touchaient" },
                { t: 217.9, texte: "작은 손톱까지 다", trad: "Jusqu'à tes petits ongles" },
                { t: 224.7, texte: "여전히 난 느낄 수 있지만", trad: "Je peux encore tout ressentir" },
                { t: 231.6, texte: "꺼진 불꽃처럼", trad: "Comme une flamme qui s'éteint" },
                { t: 238.4, texte: "타들어간 우리 사랑", trad: "Notre amour s'est consumé" },
                { t: 245.3, texte: "모두 다 너무 아프지만", trad: "Tout cela fait tellement mal" },
                { t: 252.1, texte: "이젠 널 추억이라 부를게", trad: "Mais maintenant, je t'appellerai 'un souvenir'" },
                { t: 259.0, texte: "♪ Fin", trad: "♪ Fin" }
            ]
        }
    ]
};

